import { Cairo, Noto_Sans_Arabic } from "next/font/google";
import "./globals.css";
import Header from "../components/shared/Topbar";
import Footer from "../components/shared/Footer";
import MarginLabels from "../lib/MarginLabels";

const cairo = Cairo({
  subsets: ["latin", "arabic"],
  variable: "--font-cairo",
  weight: ["300", "400", "500", "600", "700"],
});

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic", "latin"],
  variable: "--font-noto-sans-arabic",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Nartaquee",
  description: "Generated by create next app",
};




export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.variable} ${notoSansArabic.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
