import { Cairo, Noto_Sans_Arabic } from "next/font/google";
import "antd/dist/reset.css";
import "./globals.css";
import Header from "../components/shared/Topbar";
import Footer from "../components/shared/Footer";
import { UserProvider } from "../lib/useUser.jsx";
import Providers from "../components/utils/Store/Provider.jsx";
import { Toaster } from "react-hot-toast";
import ScrollToTop from "../components/ScrollToTop/ScrollToTop";
import Shared from "./../components/shared/Shared";
import FloatingCompletionRateButton from "../components/shared/FloatingCompletionRateButton";

const cairo = Cairo({
  subsets: ["latin", "arabic"],
  variable: "--font-cairo",
  weight: ["300", "400", "500", "600", "700"],
});

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic", "latin"],
  variable: "--font-noto-sans-arabic",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Ma'an Nartaqi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.variable} ${notoSansArabic.variable}`}>
        <Providers>
          <UserProvider>
            {/* ✅ Big creative Toaster */}
            <Toaster
              position="top-center"
              reverseOrder={false}
              gutter={12}
              containerStyle={{
                top: 14,
                left: 14,
                right: 14,
                pointerEvents: "none", // so it doesn't block UI
              }}
              toastOptions={{
                duration: 4000,
                className: "toast-card",
                style: {
                  pointerEvents: "auto",
                  width: "min(420px, 100%)",
                  padding: 0,
                },
                
                success: { className: "toast-card toast-success" },
                error: { className: "toast-card toast-error" },
                loading: { className: "toast-card toast-loading" },
              }}
            />

            <Header />
            <Shared />
            <ScrollToTop />
            <div className="min-h-[100svh]">{children}</div>
            <Footer />
        <FloatingCompletionRateButton  href="/course-rate" />
          </UserProvider>
        </Providers>

      </body>
    </html>
  );
}
