import { Cairo, Noto_Sans_Arabic } from "next/font/google";
import "antd/dist/reset.css";
import "./globals.css";
import Header from "../components/shared/Topbar";
import Footer from "../components/shared/Footer";
import { UserProvider } from "../lib/useUser.jsx";
import MarginLabels from "../lib/MarginLabels";
import Providers from "../components/utils/Store/Provider.jsx";
import { Toaster } from "react-hot-toast";

const cairo = Cairo({
  subsets: ["latin", "arabic"],
  variable: "--font-cairo",
  weight: ["300", "400", "500", "600", "700"],
});

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic", "latin"],
  variable: "--font-noto-sans-arabic",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Ma'an Nartaqi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.variable} ${notoSansArabic.variable}`}>
        <Providers>
          {" "}
          <UserProvider>
            <Toaster position="top-right" toastOptions={{ duration: 3000 }} />
            <Header />
            {children}
            <Footer />
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
